### ISSUE TITLE
Random NPE

### ISSUE THREAD

**Issue by ISibboI** [ISibboI/AgentSim#41]
Commit 28536ca3baaa8464ba6778cc14d6adacbbe46ee5

12:11:15.165 [main] INFO  de.isibboi.agentsim.Settings - Settings loaded
12:11:15.368 [main] INFO  de.isibboi.agentsim.ui.DrawFrame - Page flipping supported: true
12:11:15.368 [main] INFO  de.isibboi.agentsim.ui.DrawFrame - Requires full screen for page flipping: false
12:11:15.501 [main] INFO  de.isibboi.agentsim.game.MultiThreadedEntityCollider - Entity collider threads started
12:11:15.565 [main] INFO  de.isibboi.agentsim.game.Game - Game started
12:11:15.634 [main] TRACE de.isibboi.agentsim.game.entities.ai.tasks.MoveToTask - Could not find a valid path.
Exception in thread "main" java.lang.NullPointerException
	at de.isibboi.agentsim.game.entities.ai.tasks.MoveToTask.isFinished(MoveToTask.java:72)
	at de.isibboi.agentsim.game.entities.ai.TaskExecutingAI.update(TaskExecutingAI.java:56)
	at de.isibboi.agentsim.game.entities.ai.TaskExecutingAI.startNextTask(TaskExecutingAI.java:118)
	at de.isibboi.agentsim.game.entities.ai.TaskExecutingAI.update(TaskExecutingAI.java:62)
	at de.isibboi.agentsim.game.entities.ai.TaskExecutingAI.startNextTask(TaskExecutingAI.java:132)
	at de.isibboi.agentsim.game.entities.ai.TaskExecutingAI.update(TaskExecutingAI.java:62)
	at de.isibboi.agentsim.game.entities.Goblin.update(Goblin.java:72)
	at de.isibboi.agentsim.game.entities.Entities.update(Entities.java:119)
	at de.isibboi.agentsim.game.Game.update(Game.java:50)
	at de.isibboi.agentsim.ui.AgentFrame.update(AgentFrame.java:110)
	at de.isibboi.agentsim.AgentSim.run(AgentSim.java:58)
	at de.isibboi.agentsim.AgentSim.main(AgentSim.java:25)

**Comment by ISibboI** [comment]
Same as #40, just forgot to push.
